### ISSUE TITLE
Warn (optionally error) when there are duplicate ids

### ISSUE THREAD

**Issue by chambm** [fastobo/fastobo-validator#39]
It's syntactically valid for 2 terms to have the same id, but I suspect this is almost always an error. Could you add a warning in that case and allow making the warning fatal? Thanks for the easy to use tool!

**Comment by althonos** [comment]
That's a good idea, i'll try to implement that as soon as I can!

**Comment by althonos** [comment]
I have added a `--duplicates` flag to report errors if several frames are encountered that share the same ID. You can use it with `v0.3.0`. I will maybe add a warning later (the current architecture doesn't support warnings so I'll have to invest more time for these).
