### ISSUE TITLE
Executable file for fastobo-validator

### ISSUE THREAD

**Issue by fanavarro** [fastobo/fastobo-validator#4]
Hi, I find this fastobo-validator very useful and I would like to use it. Nonetheless, I do not have experience with Rust programming language and I am not very sure about how to compile the source code to obtain the executable file. Could you please provide a brief explanation about how to do that? Is the executable available directly? I also would suggest to include the binary file together with the releases, if possible.

Thanks for your time.
Francisco Abad.

**Comment by fanavarro** [comment]
Finally I have found the executable files. I am showing screenshots in order to obtain the executable file:
First you have to click in this "binaries" button, which is appearing in the readme:
![image](https://user-images.githubusercontent.com/11376639/61700866-7fc8ff00-ad3d-11e9-89ed-dfd1f0e96c17.png)

Then, you have to click in this link:
![image](https://user-images.githubusercontent.com/11376639/61700971-a5ee9f00-ad3d-11e9-9d4c-aa4f3f997413.png)

Here you have a list of versions with the binaries inside:
![image](https://user-images.githubusercontent.com/11376639/61701036-c880b800-ad3d-11e9-9963-b513c41fc95a.png)

I hope this helps somebody.

**Comment by althonos** [comment]
Hi @fanavarro, thanks for the feedback about distribution, I'll make that clearer on the `README` for people not familiar with Bintray.
