### ISSUE TITLE
Incomplete validation for replaced by?

### ISSUE THREAD

**Issue by matentzn** [fastobo/fastobo-validator#47]
I have a case like this in OWL:

```
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/zeco.owl/ZECO_0000123">
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/ZECO_0000123"/>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
```

This gets (which is terrible, but not a fastobo problem) translated to:

```
[Term]
id: ZECO:0000123
replaced_by: ZECO:0000123
```

This will cause OBO-Edit to choke, because `Attempted to specify replaced_by value for non-obsolete object bacterial treatment by gavage.`

Shouldn't fastobo catch this? Not sure, but it currently does not..

**Comment by althonos** [comment]
Well, syntactically, it's valid :smile: 

But it should be easy to add some code so that `replaced_by` and `consider` can only be present in frames for obsolete terms.

**Comment by matentzn** [comment]
Whatever you believe is best! My main use of fastobo is to make sure that the OBO file is parseable by OBO-Edit, so I thought I would let you know. This is a case that rarely happens in practice, but if it does, its really hard to debug..

**Comment by althonos** [comment]
It falls under the same case as #39: it's allowed by the OBO syntax, but 99% of the cases are bugs, so I can implement that, but the check behind a CLI flag.

**Comment by matentzn** [comment]
I am super happy for this to be a warning! At least in my case, I don't use fastobo too much in CI (although I probably should), I just run it locally when developing a new OBO format product..  I am sure your solution will be fine!

**Comment by althonos** [comment]
I released `v0.4.0`, with the `--obsoletion` / `-O` flag enabled (or the `--all` flag, because the CLI starts having too many flags to remember independently), running it on your example file would give the following error:
```
     Parsing `test.obo`
    Finished parsing `test.obo` in 0.00s
      Failed validation of `test.obo` (1 errors)
         --> in frame ZECO:0000123
             non-obsolete entity contains 1 `replaced_by` clause(s)
```

**Comment by matentzn** [comment]
Yeah sorry, I meant, will it print a warning without causing an error? Or some kind of info message?

**Comment by matentzn** [comment]
I am asking because I will need to basically remember to add that parameter everywhere :P sorry just checking!

**Comment by matentzn** [comment]
Wait nooow I see you already made a release!! Awesome! :) No worries then! Thank you!

**Comment by althonos** [comment]
Basically it will not output anything unless you explicitly turn on the error. 

> I am asking because I will need to basically remember to add that parameter everywhere :P sorry just checking!

That's why I added the `--all` flag :wink:

**Comment by matentzn** [comment]
Thank you again! :)
