### ISSUE TITLE
Problems with bintray location

### ISSUE THREAD

**Issue by matentzn** [fastobo/fastobo-validator#61]
@althonos Just to make sure: is it ok to switch ODK download location like:

![image](https://user-images.githubusercontent.com/7070631/116993002-c697a700-acce-11eb-87de-4dc10ec1e6b6.png)

Thanks

**Comment by althonos** [comment]
Yes, it should be fine!

**Comment by matentzn** [comment]
Thanks @althonos :) Great day.
